% This is the main file. It calls the petsc executable with a parameter
% generated by the user from here

close all;

N = 200;
np = 3;

status = CallPetsc(np,N,N);
[x,y] = ProcessOutput();

fprintf('x = %f, y = %f\n',x,y);